version: '3'

services:
  database:
    image: mariadb:10
    ports:
      - 3310:3306
    environment:
      MARIADB_DATABASE: uploader_db
      MARIADB_ROOT_PASSWORD: LmdNj2
    volumes:
      - database-data:/var/lib/mysql
    restart: on-failure
    networks:
      - main

  storage:
    image: minio/minio
    command: server /data --address :4000 --console-address :4010
    ports:
      - 4000:4000
      - 4010:4010
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: KlQi8c9I
    volumes:
      - storage-data:/data
    restart: on-failure
    networks:
      - main

volumes:
  database-data:
  storage-data:

networks:
  main:
    driver: bridge
